kind: Deployment
apiVersion: apps/v1
metadata:
  name: https-rest-auth
  namespace: allotr
  labels:
    app: https-rest-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-rest-auth
  template:
    metadata:
      labels:
        app: https-rest-auth
    spec:
      containers:
        - name: https-rest-auth
          image: rafaelpernil/https-rest-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 1Gi
              cpu: "500m"
            requests:
              memory: 1Gi
              cpu: "250m"
          env:
            - name:  GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  GOOGLE_CLIENT_ID
            - name:  GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  GOOGLE_CLIENT_SECRET
            - name:  GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  GOOGLE_CALLBACK_URL
            - name:  WHITELIST_MODE
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  WHITELIST_MODE
            - name:  SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  SESSION_SECRET
            - name:  REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  REDIRECT_URL
            - name:  MONGO_DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  MONGO_DB_ENDPOINT
            - name:  REDIS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  REDIS_ENDPOINT
            - name:  REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  REDIS_PORT
            - name:  DB_NAME
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  DB_NAME
            - name:  HTTPS_PORT
              valueFrom:
                secretKeyRef:
                  name:  https-rest-auth-secret
                  key:  HTTPS_PORT
      restartPolicy: Always
